package main

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

import "fmt"

const MAX int = 4000000

func main() {
	fmt.Println("doing eiler 2")

	x := 1
	y := 2
	sum := 0

	for y < MAX {
		z := x + y
		x = y
		y = z

		fmt.Printf("result: %d - %d \n", x, y)

		if z%2 == 0 {
			sum += z
		}

	}

	fmt.Printf("result: %d\n", sum)
	fmt.Println("done")

}
